version: '3.8'

services:
  api:
    build:
      context: ./py_poke_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./pokedex
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
